title: Picol Project
description: Documentation for the Picol project
remote_theme: pages-themes/midnight@v0.2.0
baseurl: "/picol" # Changed to match repository name
url: "https://zjb1001.github.io" # Updated to match your GitHub username
repository: "zjb1001/picol" # Updated to your GitHub username/repo format

# Enable GitHub Pages features
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_links:
  enabled: true
  collections: true
  permalink: /:path/:basename:output_ext

# Exclude certain files from the build
exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata

# Navigation
header_pages:
  - introduction.md
  - getting-started.md
  - reference/README.md
  - architecture.md
  - testing.md
  - contributing.md

# Include all files
include:
  - "*.md"
  - "**/*.md"
  - "assets/"

# Navigation settings (fixed duplicated entries and ensured proper paths)
nav:
  - Home: /
  - Introduction: introduction.html
  - Getting Started: getting-started.html
  - Language Reference: reference/
  - Architecture: architecture.html
  - Testing: testing.html
  - Project Structure: project_structure.html
  - Contributing: contributing.html

# Custom settings
custom:
  logo: /assets/images/logo.png
  footer: "© 2023 Picol Project"

github:
  is_project_page: true