title: Picol Project
description: Documentation for the Picol project
remote_theme: pages-themes/midnight@v0.2.0
baseurl: ""
repository: "page/picol" # Add repository information

# Enable GitHub Pages features
markdown: GFM
relative_links:
  enabled: true
  collections: true

# Exclude certain files from the build
exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata

# Navigation
header_pages:
  - introduction.md
  - getting-started.md
  - reference/README.md
  - architecture.md
  - testing.md
  - contributing.md

# Include all files
include:
  - "*.md"
  - "**/*.md"
  - "assets/"

# Navigation settings
nav:
  - Home: index.md
  - Project Structure: project_structure.md

# Custom settings
custom:
  logo: /assets/images/logo.png
  footer: "© 2023 Picol Project"

github:
  is_project_page: true