title: Picol Documentation
description: Documentation for Picol - a tiny Tcl interpreter
remote_theme: pages-themes/midnight@v0.2.0

# Enable GitHub Pages features
markdown: GFM
relative_links:
  enabled: true
  collections: true

# Exclude certain files from the build
exclude:
  - README.md
  - .gitignore

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-sitemap

# Navigation
header_pages:
  - introduction.md
  - getting-started.md
  - reference/README.md
  - architecture.md
  - testing.md
  - contributing.md

# Include all files
include:
  - "*.md"
  - "**/*.md"
  - "assets/"

# Navigation settings
nav:
  - Home: index.md
  - Project Structure: project_structure.md

# Custom settings
custom:
  logo: /assets/images/logo.png
  footer: "© 2023 Picol Project"