name: Deploy Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Create Gemfile if not exists
        run: |
          if [ ! -f Gemfile ]; then
            echo 'source "https://rubygems.org"' > Gemfile
            echo 'gem "jekyll", "~> 4.2.0"' >> Gemfile
            echo 'gem "webrick", "~> 1.7"' >> Gemfile
            echo 'group :jekyll_plugins do' >> Gemfile
            echo '  gem "jekyll-feed", "~> 0.15.1"' >> Gemfile
            echo '  gem "jekyll-seo-tag", "~> 2.7.1"' >> Gemfile
            echo 'end' >> Gemfile
          fi

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build the site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4